"""Local-RAG control endpoints for the desktop sidecar.

Two routes, both gated by :func:`require_desktop_mode` so they return
404 in server mode and are subject to the loopback-token middleware in
desktop mode:

* ``GET  /api/v1/rag/status`` — reports whether the retrieval layer can
  serve queries right now (key configured + permission granted) and how
  many local items currently carry embeddings.
* ``POST /api/v1/rag/search`` — embeds ``query`` and returns the top-k
  PII-scrubbed snippets from :class:`ContentStore`.

The chat-time path uses the same :class:`LocalRAGRetriever`; these
routes exist so the shell can render a stand-alone "Ask your local feed"
panel without going through the chat session machinery.
"""

from __future__ import annotations

import logging
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from app.api.deps import require_desktop_mode
from app.local.content_store import ContentStore, get_content_store
from app.local.embedding_provider import (
    EmbeddingUnavailable,
    LocalEmbeddingProvider,
)
from app.local.rag_jobs import ReindexJob, ReindexJobManager, get_reindex_jobs
from app.local.rag_retriever import (
    LocalRAGRetriever,
    RetrievedSnippet,
    get_rag_retriever,
)

logger = logging.getLogger(__name__)

router = APIRouter(dependencies=[Depends(require_desktop_mode)])


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class RAGStatusResponse(BaseModel):
    available: bool = Field(
        ...,
        description="True when the embedding provider is configured AND the USE_LLM_KEY permission is granted.",
    )
    indexed_count: int = Field(
        ..., description="Number of locally stored items that carry an embedding."
    )
    current_version: Optional[str] = Field(
        None,
        description="Identifier (``provider:model``) of the embedding model currently configured. "
                    "Null when no embedder is available.",
    )
    stale_count: int = Field(
        0,
        description="Items whose embedding is missing OR was generated by a prior model "
                    "(i.e. would be re-embedded by the next ``/reindex`` run).",
    )


class RAGSearchRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=4_000)
    k: int = Field(6, ge=1, le=20)
    min_score: float = Field(0.0, ge=-1.0, le=1.0)
    platforms: Optional[List[str]] = Field(
        None,
        description="Optional list of SourcePlatform values to restrict the search to.",
    )


class RAGSnippet(BaseModel):
    content_id: str
    title: str
    source_url: str
    source_platform: str
    published_at: float
    score: float
    text: str
    base_score: float = 0.0
    personalization_bonus: float = 0.0


class RAGSearchResponse(BaseModel):
    query: str
    snippets: List[RAGSnippet]


# ---------------------------------------------------------------------------
# Personalization schemas
# ---------------------------------------------------------------------------


class RAGFeedbackRequest(BaseModel):
    content_id: str = Field(..., min_length=1, max_length=128)
    score: float = Field(
        ..., ge=-1.0, le=1.0,
        description="Use +1.0 for thumbs-up, -1.0 for thumbs-down. "
                    "Fractional values are accepted to support a slider UI; "
                    "the signals store clamps the running total on its side.",
    )


class RAGFeedbackResponse(BaseModel):
    content_id: str
    feedback_total: float = Field(
        ...,
        description="Running total of feedback after this update (clamped by the store).",
    )


class RAGSignalRow(BaseModel):
    content_id: str
    cited: int
    feedback: float
    last_seen: float


class RAGSignalsResponse(BaseModel):
    count: int
    rows: List[RAGSignalRow]


class RAGSignalsClearResponse(BaseModel):
    cleared: int


class RAGTelemetryResponse(BaseModel):
    """Per-process personalization counters surfaced for the UX panel."""

    queries_total: int = Field(
        ..., description="Every call to LocalRAGRetriever.retrieve that produced a hit OR an empty result.",
    )
    queries_personalized: int = Field(
        ...,
        description="Subset of ``queries_total`` where ``personalize`` was on AND at least one "
                    "candidate received a non-zero personalization bonus.",
    )
    queries_reordered: int = Field(
        ...,
        description="Subset of ``queries_personalized`` where the post-rerank top-k order "
                    "differed from the pure cosine baseline.",
    )
    queries_promoted_to_top: int = Field(
        ...,
        description="Subset of ``queries_reordered`` where the #1 result changed identity \u2014 "
                    "the strongest signal that personalization is materially affecting the user.",
    )
    signal_lookups_failed: int = Field(
        ...,
        description="Counter of personalization queries where loading the signals DB raised. "
                    "Always > 0 indicates a disk-level fault; the ranker continued without signals.",
    )


class RAGTelemetryResetResponse(BaseModel):
    reset: bool


class RAGReindexRequest(BaseModel):
    max_items: int = Field(
        500, ge=1, le=5_000,
        description="Upper bound on the number of items embedded in this call. "
                    "Caller polls again to drain the remainder.",
    )
    batch_size: int = Field(
        16, ge=1, le=128,
        description="Number of texts sent per embedding API call.",
    )


class RAGReindexResponse(BaseModel):
    scanned: int = Field(..., description="Items pulled from the store for this run.")
    embedded: int = Field(..., description="Items whose embedding was successfully persisted.")
    skipped: int = Field(
        0,
        description="Items that cannot be embedded (e.g. empty title and body). "
                    "When ``embedded == 0`` and ``skipped == scanned`` the caller "
                    "should stop polling \u2014 the remaining rows will never make progress.",
    )
    errors: int = Field(..., description="Items that failed embedding or persistence.")
    remaining: int = Field(
        ...,
        description="Items that are still missing an embedding OR pinned to a prior model "
                    "(would be picked up by the next call).",
    )


class RAGReindexStartRequest(BaseModel):
    batch_size: int = Field(
        16, ge=1, le=128,
        description="Number of texts sent per embedding API call.",
    )


class RAGReindexJobStatus(BaseModel):
    id: str
    status: str = Field(
        ..., description="One of: queued, running, done, cancelled, error.",
    )
    scanned: int
    embedded: int
    skipped: int
    errors: int
    total: int
    batch_size: int
    started_at: Optional[float]
    finished_at: Optional[float]
    detail: Optional[str] = None


class RAGReindexJobsResponse(BaseModel):
    jobs: List[RAGReindexJobStatus]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


def _retriever() -> LocalRAGRetriever:
    return get_rag_retriever()


def _embedder() -> LocalEmbeddingProvider:
    """Resolve the embedder used by the backfill route.

    Delegates to the same provider the retriever already holds so the
    backfill respects the same BYOK / permission / scrubbing contract as
    the chat-time path.  Exposed as a module-level seam so tests can
    inject a fake without monkey-patching :class:`LocalRAGRetriever`.
    """
    return _retriever()._embedder  # type: ignore[attr-defined]


def _store() -> ContentStore:
    return get_content_store()


@router.get("/status", response_model=RAGStatusResponse)
async def get_status() -> RAGStatusResponse:
    r = _retriever()
    # The embedder may be unreachable (no key / denied permission); we
    # still expose ``stale_count`` based on missing embeddings so the UI
    # can render "X items pending" even before the user grants the key.
    current_version: Optional[str] = None
    try:
        current_version = _embedder().model
    except Exception:  # noqa: BLE001 - status must never raise
        current_version = None
    return RAGStatusResponse(
        available=r.is_available(),
        indexed_count=r.indexed_count(),
        current_version=current_version,
        stale_count=_store().count_stale_embeddings(current_version),
    )


@router.post("/search", response_model=RAGSearchResponse)
async def search(request: RAGSearchRequest) -> RAGSearchResponse:
    from app.core.models import SourcePlatform  # local import keeps this route cheap at import time

    platforms = None
    if request.platforms:
        try:
            platforms = [SourcePlatform(p) for p in request.platforms]
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"unknown platform value: {exc}",
            )
    r = _retriever()
    snippets: List[RetrievedSnippet] = await r.retrieve(
        request.query, k=request.k, platforms=platforms, min_score=request.min_score,
    )
    return RAGSearchResponse(
        query=request.query,
        snippets=[RAGSnippet(**s.to_dict()) for s in snippets],
    )


async def _run_reindex_batches(
    *,
    store: ContentStore,
    embedder: LocalEmbeddingProvider,
    current_version: Optional[str],
    max_items: int,
    batch_size: int,
    progress: Optional[ReindexJob] = None,
    should_cancel: Optional[callable] = None,  # type: ignore[valid-type]
) -> tuple[int, int, int, int]:
    """Drain stale embeddings in batches.  Shared by sync + background paths.

    Returns ``(scanned, embedded, skipped, errors)``.  When ``progress`` is
    provided each batch updates its counters in-place so a UI poll can see
    incremental progress.  When ``should_cancel`` returns True the loop
    exits cleanly between batches.
    """
    pending = store.list_stale_embeddings(current_version, limit=max_items)
    scanned = len(pending)
    if progress is not None:
        progress.total = max(progress.total, scanned)
    embedded = 0
    errors = 0
    skipped = 0
    for offset in range(0, scanned, batch_size):
        if should_cancel is not None and should_cancel():
            break
        chunk = pending[offset: offset + batch_size]
        # Filter out rows with no usable text — they cannot be embedded
        # and would otherwise be re-pulled forever, leaving the UI
        # convinced there is work remaining.
        prepared = [(cid, ((title or "") + "\n" + (raw or "")).strip())
                    for cid, title, raw in chunk]
        usable = [(cid, text) for cid, text in prepared if text]
        skipped += len(prepared) - len(usable)
        if not usable:
            if progress is not None:
                progress.scanned += len(prepared)
                progress.skipped = skipped
            continue
        try:
            vectors = await embedder.embed_batch([t for _, t in usable])
        except EmbeddingUnavailable as exc:
            # Permission revoked mid-run: abort cleanly with what we got.
            logger.warning("reindex aborted: %s", exc)
            errors += len(usable)
            break
        except Exception:  # noqa: BLE001 - per-batch isolation
            logger.exception("reindex batch failed (offset=%d)", offset)
            errors += len(usable)
            if progress is not None:
                progress.scanned += len(prepared)
                progress.errors = errors
            continue
        if len(vectors) != len(usable):
            logger.warning(
                "reindex batch returned %d vectors for %d inputs; skipping",
                len(vectors), len(usable),
            )
            errors += len(usable)
            if progress is not None:
                progress.scanned += len(prepared)
                progress.errors = errors
            continue
        for (cid, _text), vec in zip(usable, vectors):
            try:
                if store.set_embedding(cid, vec, version=current_version):
                    embedded += 1
                else:
                    errors += 1
            except Exception:  # noqa: BLE001 - per-item isolation
                logger.exception("reindex persist failed for %s", cid)
                errors += 1
        if progress is not None:
            progress.scanned += len(prepared)
            progress.embedded = embedded
            progress.errors = errors
            progress.skipped = skipped
    return scanned, embedded, skipped, errors


@router.post("/reindex", response_model=RAGReindexResponse)
async def reindex(request: RAGReindexRequest) -> RAGReindexResponse:
    """Embed up to ``max_items`` rows that currently lack an embedding.

    Returns 409 when the RAG layer is not currently available — operator
    actions must fail loudly so the UI can surface a "configure key /
    grant permission" CTA instead of silently doing nothing.
    """
    retriever = _retriever()
    if not retriever.is_available():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="RAG layer unavailable: configure an embedding key and "
                   "grant USE_LLM_KEY before running reindex.",
        )
    store = _store()
    embedder = _embedder()
    # ``model`` may raise on a misconfigured embedder; treat as no
    # version so the selector falls back to "missing only".
    try:
        current_version: Optional[str] = embedder.model
    except Exception:  # noqa: BLE001
        current_version = None
    scanned, embedded, skipped, errors = await _run_reindex_batches(
        store=store,
        embedder=embedder,
        current_version=current_version,
        max_items=request.max_items,
        batch_size=request.batch_size,
    )
    return RAGReindexResponse(
        scanned=scanned,
        embedded=embedded,
        skipped=skipped,
        errors=errors,
        remaining=store.count_stale_embeddings(current_version),
    )


# ---------------------------------------------------------------------------
# Personalization: feedback + signals transparency
# ---------------------------------------------------------------------------


@router.post("/feedback", response_model=RAGFeedbackResponse)
async def submit_feedback(request: RAGFeedbackRequest) -> RAGFeedbackResponse:
    """Record explicit user feedback on a retrieved snippet.

    Soft-fails to 0.0 on any persistence error so a flaky signals DB
    never blocks the chat surface — the route still returns 200.
    """
    r = _retriever()
    try:
        total = r.record_feedback(request.content_id, request.score)
    except Exception:  # noqa: BLE001 - signals must never break the UI
        logger.exception("feedback persist failed for %s", request.content_id)
        total = 0.0
    return RAGFeedbackResponse(content_id=request.content_id, feedback_total=total)


@router.get("/signals", response_model=RAGSignalsResponse)
async def list_signals(limit: int = 50) -> RAGSignalsResponse:
    """Top personalization signals, surfaced for transparency / debug.

    The desktop UI is expected to render these in a "Why am I seeing this?"
    drawer so the user can see exactly which items have accumulated
    citation / feedback weight against their session.
    """
    limit = max(1, min(int(limit), 500))
    r = _retriever()
    rows = r.signals_store.list_top(limit=limit)
    return RAGSignalsResponse(
        count=r.signals_store.count(),
        rows=[
            RAGSignalRow(
                content_id=row["content_id"],
                cited=int(row.get("cited", 0)),
                feedback=float(row.get("feedback", 0.0)),
                last_seen=float(row.get("last_seen", 0.0)),
            )
            for row in rows
        ],
    )


@router.delete("/signals", response_model=RAGSignalsClearResponse)
async def clear_signals() -> RAGSignalsClearResponse:
    """Wipe all personalization signals.  Useful for "reset my preferences"."""
    r = _retriever()
    cleared = r.signals_store.clear()
    return RAGSignalsClearResponse(cleared=cleared)


@router.get("/telemetry", response_model=RAGTelemetryResponse)
async def get_telemetry() -> RAGTelemetryResponse:
    """Return per-process personalization counters.

    The desktop sidecar is short-lived (one process per launch) so these
    counters are not persisted.  The UX panel uses them to display a
    "personalization affected N% of your recent searches" tile.
    """
    snap = _retriever().telemetry_snapshot()
    return RAGTelemetryResponse(**snap)


@router.delete("/telemetry", response_model=RAGTelemetryResetResponse)
async def reset_telemetry() -> RAGTelemetryResetResponse:
    """Zero every telemetry counter.  Used by the "start fresh" UX action."""
    _retriever().reset_telemetry()
    return RAGTelemetryResetResponse(reset=True)


# ---------------------------------------------------------------------------
# Background reindex jobs
# ---------------------------------------------------------------------------


def _jobs() -> ReindexJobManager:
    return get_reindex_jobs()


def _job_to_status(job: ReindexJob) -> RAGReindexJobStatus:
    d = job.to_dict()
    return RAGReindexJobStatus(**d)


@router.post(
    "/reindex/jobs",
    response_model=RAGReindexJobStatus,
    status_code=status.HTTP_202_ACCEPTED,
)
async def start_reindex_job(
    request: RAGReindexStartRequest,
) -> RAGReindexJobStatus:
    """Kick off a fire-and-forget reindex over *all* stale rows.

    Returns ``202 Accepted`` with the job snapshot; the UI polls
    ``GET /reindex/jobs/{id}`` for progress.  Returns 409 when the
    RAG layer is unavailable or when another job is already running.
    """
    retriever = _retriever()
    if not retriever.is_available():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="RAG layer unavailable: configure an embedding key and "
                   "grant USE_LLM_KEY before scheduling a reindex job.",
        )
    store = _store()
    embedder = _embedder()
    try:
        current_version: Optional[str] = embedder.model
    except Exception:  # noqa: BLE001
        current_version = None
    total = store.count_stale_embeddings(current_version)

    async def worker(job: ReindexJob, should_cancel) -> None:
        # Drain in chunks so a corpus of 100k rows can still complete
        # without holding the entire candidate list in memory.
        page = max(1, min(2_000, job.batch_size * 32))
        while not should_cancel():
            scanned, _emb, _skp, _err = await _run_reindex_batches(
                store=store,
                embedder=embedder,
                current_version=current_version,
                max_items=page,
                batch_size=job.batch_size,
                progress=job,
                should_cancel=should_cancel,
            )
            if scanned == 0:
                break

    try:
        job = _jobs().start(worker, batch_size=request.batch_size, total=total)
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT, detail=str(exc),
        )
    return _job_to_status(job)


@router.get("/reindex/jobs", response_model=RAGReindexJobsResponse)
async def list_reindex_jobs() -> RAGReindexJobsResponse:
    return RAGReindexJobsResponse(
        jobs=[_job_to_status(j) for j in _jobs().list()],
    )


@router.get("/reindex/jobs/{job_id}", response_model=RAGReindexJobStatus)
async def get_reindex_job(job_id: str) -> RAGReindexJobStatus:
    job = _jobs().get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"no reindex job with id {job_id!r}",
        )
    return _job_to_status(job)


@router.delete("/reindex/jobs/{job_id}", response_model=RAGReindexJobStatus)
async def cancel_reindex_job(job_id: str) -> RAGReindexJobStatus:
    mgr = _jobs()
    job = mgr.get(job_id)
    if job is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"no reindex job with id {job_id!r}",
        )
    mgr.cancel(job_id)
    return _job_to_status(job)
