"""Local-RAG control endpoints for the desktop sidecar.

Two routes, both gated by :func:`require_desktop_mode` so they return
404 in server mode and are subject to the loopback-token middleware in
desktop mode:

* ``GET  /api/v1/rag/status`` — reports whether the retrieval layer can
  serve queries right now (key configured + permission granted) and how
  many local items currently carry embeddings.
* ``POST /api/v1/rag/search`` — embeds ``query`` and returns the top-k
  PII-scrubbed snippets from :class:`ContentStore`.

The chat-time path uses the same :class:`LocalRAGRetriever`; these
routes exist so the shell can render a stand-alone "Ask your local feed"
panel without going through the chat session machinery.
"""

from __future__ import annotations

import logging
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from app.api.deps import require_desktop_mode
from app.local.content_store import ContentStore, get_content_store
from app.local.embedding_provider import (
    EmbeddingUnavailable,
    LocalEmbeddingProvider,
)
from app.local.rag_retriever import (
    LocalRAGRetriever,
    RetrievedSnippet,
    get_rag_retriever,
)

logger = logging.getLogger(__name__)

router = APIRouter(dependencies=[Depends(require_desktop_mode)])


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class RAGStatusResponse(BaseModel):
    available: bool = Field(
        ...,
        description="True when the embedding provider is configured AND the USE_LLM_KEY permission is granted.",
    )
    indexed_count: int = Field(
        ..., description="Number of locally stored items that carry an embedding."
    )
    current_version: Optional[str] = Field(
        None,
        description="Identifier (``provider:model``) of the embedding model currently configured. "
                    "Null when no embedder is available.",
    )
    stale_count: int = Field(
        0,
        description="Items whose embedding is missing OR was generated by a prior model "
                    "(i.e. would be re-embedded by the next ``/reindex`` run).",
    )


class RAGSearchRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=4_000)
    k: int = Field(6, ge=1, le=20)
    min_score: float = Field(0.0, ge=-1.0, le=1.0)
    platforms: Optional[List[str]] = Field(
        None,
        description="Optional list of SourcePlatform values to restrict the search to.",
    )


class RAGSnippet(BaseModel):
    content_id: str
    title: str
    source_url: str
    source_platform: str
    published_at: float
    score: float
    text: str


class RAGSearchResponse(BaseModel):
    query: str
    snippets: List[RAGSnippet]


class RAGReindexRequest(BaseModel):
    max_items: int = Field(
        500, ge=1, le=5_000,
        description="Upper bound on the number of items embedded in this call. "
                    "Caller polls again to drain the remainder.",
    )
    batch_size: int = Field(
        16, ge=1, le=128,
        description="Number of texts sent per embedding API call.",
    )


class RAGReindexResponse(BaseModel):
    scanned: int = Field(..., description="Items pulled from the store for this run.")
    embedded: int = Field(..., description="Items whose embedding was successfully persisted.")
    skipped: int = Field(
        0,
        description="Items that cannot be embedded (e.g. empty title and body). "
                    "When ``embedded == 0`` and ``skipped == scanned`` the caller "
                    "should stop polling \u2014 the remaining rows will never make progress.",
    )
    errors: int = Field(..., description="Items that failed embedding or persistence.")
    remaining: int = Field(
        ...,
        description="Items that are still missing an embedding OR pinned to a prior model "
                    "(would be picked up by the next call).",
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


def _retriever() -> LocalRAGRetriever:
    return get_rag_retriever()


def _embedder() -> LocalEmbeddingProvider:
    """Resolve the embedder used by the backfill route.

    Delegates to the same provider the retriever already holds so the
    backfill respects the same BYOK / permission / scrubbing contract as
    the chat-time path.  Exposed as a module-level seam so tests can
    inject a fake without monkey-patching :class:`LocalRAGRetriever`.
    """
    return _retriever()._embedder  # type: ignore[attr-defined]


def _store() -> ContentStore:
    return get_content_store()


@router.get("/status", response_model=RAGStatusResponse)
async def get_status() -> RAGStatusResponse:
    r = _retriever()
    # The embedder may be unreachable (no key / denied permission); we
    # still expose ``stale_count`` based on missing embeddings so the UI
    # can render "X items pending" even before the user grants the key.
    current_version: Optional[str] = None
    try:
        current_version = _embedder().model
    except Exception:  # noqa: BLE001 - status must never raise
        current_version = None
    return RAGStatusResponse(
        available=r.is_available(),
        indexed_count=r.indexed_count(),
        current_version=current_version,
        stale_count=_store().count_stale_embeddings(current_version),
    )


@router.post("/search", response_model=RAGSearchResponse)
async def search(request: RAGSearchRequest) -> RAGSearchResponse:
    from app.core.models import SourcePlatform  # local import keeps this route cheap at import time

    platforms = None
    if request.platforms:
        try:
            platforms = [SourcePlatform(p) for p in request.platforms]
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"unknown platform value: {exc}",
            )
    r = _retriever()
    snippets: List[RetrievedSnippet] = await r.retrieve(
        request.query, k=request.k, platforms=platforms, min_score=request.min_score,
    )
    return RAGSearchResponse(
        query=request.query,
        snippets=[RAGSnippet(**s.to_dict()) for s in snippets],
    )


@router.post("/reindex", response_model=RAGReindexResponse)
async def reindex(request: RAGReindexRequest) -> RAGReindexResponse:
    """Embed up to ``max_items`` rows that currently lack an embedding.

    Returns 409 when the RAG layer is not currently available — operator
    actions must fail loudly so the UI can surface a "configure key /
    grant permission" CTA instead of silently doing nothing.
    """
    retriever = _retriever()
    if not retriever.is_available():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="RAG layer unavailable: configure an embedding key and "
                   "grant USE_LLM_KEY before running reindex.",
        )
    store = _store()
    embedder = _embedder()
    # ``model`` may raise on a misconfigured embedder; treat as no
    # version so the selector falls back to "missing only".
    try:
        current_version: Optional[str] = embedder.model
    except Exception:  # noqa: BLE001
        current_version = None
    pending = store.list_stale_embeddings(current_version, limit=request.max_items)
    scanned = len(pending)
    embedded = 0
    errors = 0
    skipped = 0
    for offset in range(0, scanned, request.batch_size):
        chunk = pending[offset: offset + request.batch_size]
        # Filter out rows with no usable text — they cannot be embedded
        # and would otherwise be re-pulled forever, leaving the UI
        # convinced there is work remaining.
        prepared = [(cid, ((title or "") + "\n" + (raw or "")).strip())
                    for cid, title, raw in chunk]
        usable = [(cid, text) for cid, text in prepared if text]
        skipped += len(prepared) - len(usable)
        if not usable:
            continue
        try:
            vectors = await embedder.embed_batch([t for _, t in usable])
        except EmbeddingUnavailable as exc:
            # Permission revoked mid-run: abort cleanly with what we got.
            logger.warning("reindex aborted: %s", exc)
            errors += len(usable)
            break
        except Exception:  # noqa: BLE001 - per-batch isolation
            logger.exception("reindex batch failed (offset=%d)", offset)
            errors += len(usable)
            continue
        if len(vectors) != len(usable):
            logger.warning(
                "reindex batch returned %d vectors for %d inputs; skipping",
                len(vectors), len(usable),
            )
            errors += len(usable)
            continue
        for (cid, _text), vec in zip(usable, vectors):
            try:
                if store.set_embedding(cid, vec, version=current_version):
                    embedded += 1
                else:
                    errors += 1
            except Exception:  # noqa: BLE001 - per-item isolation
                logger.exception("reindex persist failed for %s", cid)
                errors += 1
    return RAGReindexResponse(
        scanned=scanned,
        embedded=embedded,
        skipped=skipped,
        errors=errors,
        remaining=store.count_stale_embeddings(current_version),
    )
