"""Visual output generators (images, infographics, videos)."""

import asyncio
import base64
import enum
import io
import logging
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

from PIL import Image, ImageDraw, ImageFont

from app.core.models import Cluster, ContentItem
from app.output.generators.base import BaseOutputGenerator
from app.output.models import (
    GeneratedOutput,
    OutputFormat,
    OutputMetadata,
    OutputPreferences,
    OutputRequest,
    VisualizationType,
)


class InfographicGenerator(BaseOutputGenerator):
    """Generate infographic images from content."""

    def __init__(self, preferences: OutputPreferences):
        """Initialize infographic generator."""
        super().__init__(preferences)
        self.width = 1200
        self.height = 1600
        self.background_color = (255, 255, 255)
        self.text_color = (33, 33, 33)
        self.accent_color = (66, 133, 244)

    async def generate(
        self,
        request: OutputRequest,
        clusters: List[Cluster],
        items: List[ContentItem],
        **kwargs,
    ) -> GeneratedOutput:
        """Generate infographic image."""
        start_time = time.time()

        # Create image
        img = Image.new("RGB", (self.width, self.height), self.background_color)
        draw = ImageDraw.Draw(img)

        # Load fonts (fallback to default if custom fonts not available)
        try:
            title_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 48)
            heading_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32)
            body_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 24)
        except (OSError, IOError) as e:
            logger.warning(f"Failed to load custom fonts, using default: {e}")
            title_font = ImageFont.load_default()
            heading_font = ImageFont.load_default()
            body_font = ImageFont.load_default()

        y_offset = 50

        # Draw title
        title = f"Intelligence Digest"
        draw.text((50, y_offset), title, fill=self.text_color, font=title_font)
        y_offset += 100

        # Draw date
        from datetime import datetime
        date_str = datetime.utcnow().strftime("%B %d, %Y")
        draw.text((50, y_offset), date_str, fill=self.accent_color, font=body_font)
        y_offset += 80

        # Draw clusters
        for i, cluster in enumerate(clusters[:5], 1):  # Max 5 clusters
            # Draw cluster number badge
            badge_x = 50
            badge_y = y_offset
            badge_radius = 20
            draw.ellipse(
                [badge_x, badge_y, badge_x + badge_radius * 2, badge_y + badge_radius * 2],
                fill=self.accent_color,
            )
            draw.text(
                (badge_x + badge_radius - 5, badge_y + 5),
                str(i),
                fill=(255, 255, 255),
                font=body_font,
            )

            # Draw cluster topic
            topic_x = badge_x + badge_radius * 2 + 20
            draw.text((topic_x, y_offset), cluster.topic[:50], fill=self.text_color, font=heading_font)
            y_offset += 50

            # Draw cluster summary (truncated)
            summary = cluster.summary[:150] + "..." if len(cluster.summary) > 150 else cluster.summary
            # Word wrap
            words = summary.split()
            lines = []
            current_line = []
            for word in words:
                current_line.append(word)
                test_line = " ".join(current_line)
                bbox = draw.textbbox((0, 0), test_line, font=body_font)
                if bbox[2] > self.width - 100:
                    current_line.pop()
                    lines.append(" ".join(current_line))
                    current_line = [word]
            if current_line:
                lines.append(" ".join(current_line))

            for line in lines[:3]:  # Max 3 lines
                draw.text((topic_x, y_offset), line, fill=self.text_color, font=body_font)
                y_offset += 35

            y_offset += 40

            if y_offset > self.height - 200:
                break

        # Draw footer
        footer_y = self.height - 100
        draw.line([(50, footer_y), (self.width - 50, footer_y)], fill=self.accent_color, width=2)
        footer_text = f"Generated by Social Media Radar • {len(items)} sources analyzed"
        draw.text((50, footer_y + 20), footer_text, fill=self.text_color, font=body_font)

        # Save to bytes
        img_bytes = io.BytesIO()
        img.save(img_bytes, format="PNG", optimize=True)
        img_bytes.seek(0)

        generation_time_ms = int((time.time() - start_time) * 1000)

        metadata = OutputMetadata(
            format=OutputFormat.IMAGE,
            generation_time_ms=generation_time_ms,
            file_size_bytes=len(img_bytes.getvalue()),
        )

        # Encode image as base64 for storage
        img_base64 = base64.b64encode(img_bytes.getvalue()).decode()

        output = GeneratedOutput(
            user_id=request.user_id,
            digest_id=request.digest_id,
            preferences_id=request.preferences_id or self.preferences.id,
            format=OutputFormat.IMAGE,
            content=img_base64,  # Base64 encoded image
            media_files={"infographic.png": img_bytes.getvalue()},
            metadata=metadata,
            title="Daily Intelligence Infographic",
        )

        metadata.quality_score = self._calculate_quality_score(output)

        return output

    async def validate_output(self, output: GeneratedOutput) -> bool:
        """Validate infographic output."""
        # Check if image was generated
        if not output.content:
            return False

        # Check file size (should be reasonable)
        if output.metadata.file_size_bytes and output.metadata.file_size_bytes > 10 * 1024 * 1024:  # 10MB
            return False

        return True


class VideoGenerationMode(str, enum.Enum):
    """Execution mode for ``VideoGenerator``.

    Values
    ------
    SCRIPT_ONLY
        Produces a structured Markdown script without rendering video.
        This is the current production-ready mode.  Downstream callers
        should use the script for TTS or human narration.
    LOCAL_RENDER
        Produces a video file using locally-installed tools (FFmpeg + TTS).
        Requires ``ffmpeg`` and a TTS backend to be installed.
    REMOTE_RENDER
        Delegates rendering to a remote video-generation API (e.g. Sora,
        Runway ML).  Requires valid API credentials.
    """
    SCRIPT_ONLY   = "script_only"
    LOCAL_RENDER  = "local_render"
    REMOTE_RENDER = "remote_render"


class VideoGenerator(BaseOutputGenerator):
    """Generate AI video summaries.

    ``VideoGenerator`` explicitly tracks its ``generation_mode`` so callers
    are never silently handed a script when they expect a rendered video.

    Args:
        preferences:      Output preferences (inherited from ``BaseOutputGenerator``).
        generation_mode:  Active execution tier.  Defaults to ``SCRIPT_ONLY``
                          (the only fully-implemented mode).  Setting
                          ``LOCAL_RENDER`` or ``REMOTE_RENDER`` without the
                          necessary dependencies or credentials raises
                          ``RuntimeError`` on first ``generate()`` call.
    """

    def __init__(
        self,
        preferences: OutputPreferences,
        generation_mode: VideoGenerationMode = VideoGenerationMode.SCRIPT_ONLY,
    ) -> None:
        """Initialize video generator."""
        super().__init__(preferences)
        if not isinstance(generation_mode, VideoGenerationMode):
            raise TypeError(
                f"'generation_mode' must be a VideoGenerationMode, "
                f"got {type(generation_mode).__name__!r}"
            )
        self._generation_mode = generation_mode

        # ── Production safety contract ────────────────────────────────────────
        # LOCAL_RENDER and REMOTE_RENDER require external renderers that may not
        # be present.  In strict mode, registering these modes at init time
        # without a real renderer is treated as a stub backend.
        if generation_mode != VideoGenerationMode.SCRIPT_ONLY:
            from app.core.production_guard import get_guard
            get_guard().require_real_backend(
                capability="video_render",
                resolved_backend="stub",
                allowed_stubs=frozenset({"stub"}),
            )

        logger.info(
            "VideoGenerator init: generation_mode=%s", generation_mode.value
        )

    @property
    def generation_mode(self) -> VideoGenerationMode:
        """The active video generation mode."""
        return self._generation_mode

    async def generate(
        self,
        request: OutputRequest,
        clusters: List[Cluster],
        items: List[ContentItem],
        **kwargs,
    ) -> GeneratedOutput:
        """Generate a video summary in the configured ``generation_mode``.

        Currently only ``SCRIPT_ONLY`` is fully implemented.  Requesting
        ``LOCAL_RENDER`` or ``REMOTE_RENDER`` raises ``NotImplementedError``
        unless the caller injects a ``renderer`` kwarg (integration hook for
        future backends).

        Args:
            request:  Output request metadata.
            clusters: Topic clusters to summarise.
            items:    Source content items.
            **kwargs: Reserved for future renderer injection
                      (``renderer`` callable for LOCAL_RENDER/REMOTE_RENDER).

        Returns:
            ``GeneratedOutput`` with the script as ``content`` and
            ``generation_mode`` recorded in ``metadata.extra_metadata``.

        Raises:
            NotImplementedError: When mode is ``LOCAL_RENDER`` or
                                 ``REMOTE_RENDER`` and no ``renderer`` kwarg
                                 is provided.
        """
        mode = self._generation_mode
        logger.info(
            "VideoGenerator.generate: mode=%s clusters=%d items=%d",
            mode.value, len(clusters), len(items),
        )
        start_time = time.time()

        if mode in (VideoGenerationMode.LOCAL_RENDER, VideoGenerationMode.REMOTE_RENDER):
            renderer = kwargs.get("renderer")
            if renderer is None:
                raise NotImplementedError(
                    f"VideoGenerator mode='{mode.value}' requires a 'renderer' "
                    "callable to be passed as a kwarg.  "
                    "Install the required backend and inject it, or use "
                    "VideoGenerationMode.SCRIPT_ONLY for the current release."
                )
            return await renderer(request, clusters, items)

        # SCRIPT_ONLY — fully implemented
        script = self._generate_script(clusters, items)
        generation_time_ms = int((time.time() - start_time) * 1000)

        metadata = OutputMetadata(
            format=OutputFormat.VIDEO,
            generation_time_ms=generation_time_ms,
            word_count=len(script.split()),
        )

        summary = (
            f"AI-generated video script ({len(clusters)} topic clusters, "
            f"{len(items)} source items). "
            f"Generation mode: {mode.value}. "
            "Render with a TTS + FFmpeg pipeline to produce the final video."
        )

        output = GeneratedOutput(
            user_id=request.user_id,
            digest_id=request.digest_id,
            preferences_id=request.preferences_id or self.preferences.id,
            format=OutputFormat.VIDEO,
            content=script,
            metadata=metadata,
            title="Daily Intelligence Video Script",
            summary=summary,
        )
        logger.debug(
            "VideoGenerator.generate: done mode=%s script_words=%d latency_ms=%d",
            mode.value, len(script.split()), generation_time_ms,
        )
        return output

    def _generate_script(self, clusters: List[Cluster], items: List[ContentItem]) -> str:
        """Generate video script."""
        script_parts = []

        script_parts.append("# Video Script: Daily Intelligence Digest\n\n")
        script_parts.append("## Opening\n")
        script_parts.append(
            f"Welcome to your daily intelligence digest. Today we're covering {len(clusters)} major topics.\n\n"
        )

        for i, cluster in enumerate(clusters[:5], 1):
            script_parts.append(f"## Segment {i}: {cluster.topic}\n")
            script_parts.append(f"{cluster.summary}\n\n")
            script_parts.append(f"[Visual: Show key statistics and sources]\n\n")

        script_parts.append("## Closing\n")
        script_parts.append(
            "That's your intelligence digest for today. Stay informed, stay ahead.\n"
        )

        return "".join(script_parts)

    async def validate_output(self, output: GeneratedOutput) -> bool:
        """Validate video output."""
        return len(output.content) > 100  # Basic validation

